version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    command:
      python3 main.py

  db:
    container_name: suitecrm
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
